# Generated by Django 5.1.7 on 2025-03-14 19:52

import authentication.custom_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.custom_manager.custom_user_manager()),
            ],
        ),
    ]
